---
# tasks file for use_mssql
- name: open port 1433 for remote access(Ubuntu)
  ufw:
    port: 1433
    proto: tcp
    rule: allow
  when: ansible_distribution == 'Ubuntu'

- name: instal pymssql
  pip: 
    name: pymssql<3.0

- name: make database
  mssql_db:
    name: my_db_3
    state: present
    login_host: localhost
    login_user: SA
    login_password: PassWord1

- name: templating sql script
  template:
    src: templates/sample.sql.j2
    dest: /tmp/sample.sql
    mode: '644'

- name: copy databse zip file to guest
  copy:
    src: ~/sample_data/caysqlseed.zip
    dest: /tmp

- name: download unzip 
  package:
    name: unzip
    state: latest

# - name: make directory
#  file:
#    path: /var/opt/mssql
#    state: directory

- name: unzip database folder contains .bak file
  unarchive:
    src: /tmp/caysqlseed.zip
    dest: /var/opt/mssql/
    remote_src: yes
    owner: packt
    group: packt
    mode: '744'

- name: import the sql file
  mssql_db:
    name: ms_repo_data
    state: import
    target: /tmp/sample.sql
    login_host: localhost
    login_user: SA
    login_password: PassWord1
    autocommit: yes












